elastic-query-service:
  version: v1
  backPressure-delay-ms: 500

server:
  port: 8183
  servlet:
    context-path: /reactive-elastic-query-service

elastic-query-config:
  text-field: text

elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000


kafka-config:
  topic-name: twitter-analytics-topic-2
#  topic-name: twitter-topic
  topic-names-to-create:
#    - twitter-topic
    - twitter-analytics-topic-2
  num-partitions: 3
  replication-factor: 3
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-servers: http://localhost:8081
  sleep-time-ms: 1000
  max-interval-ms: 10000
  retry-multiplier: 2.0
  admin-retry-max: 1


spring:
  webflux:
    base-path: /reactive-elastic-query-service
  codec:
    max-in-memory-size: 25MB
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200
          max-in-memory-size: 25MB


user-config:
  username: test
  #      password: springCloud_Pwd!
  password: '{cipher}864187498c1689c6845014ae2e538057aa7b374b5862a8604b183b5e61b23391d2cbb9b8c0118fa7039e048b3471eefe'
  roles: USER